sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '5.1'
  - '4.2.2'
  - '0.12'
  - '0.10'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
